//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Messenger_Vasanov_ISP33.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int ID_Message { get; set; }
        public int ID_Chat { get; set; }
        public int ID_Sender { get; set; }
        public string Text_content { get; set; }
        public Nullable<System.DateTime> Sent_at { get; set; }
        public Nullable<bool> Is_read { get; set; }
    
        public virtual Chats Chats { get; set; }
        public virtual Users Users { get; set; }
    }
}
